"""Structured error code constants.

RULE-API04: Error codes MUST be structured and predictable.
"""


class ErrorCode:
    """Standard error codes used in API responses."""

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    NOT_FOUND = "NOT_FOUND"

    # Authentication & Authorization
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"

    # User & Profile
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
    INVALID_OTP = "INVALID_OTP"

    # Classroom
    CLASSROOM_NOT_FOUND = "CLASSROOM_NOT_FOUND"
    INVALID_JOIN_CODE = "INVALID_JOIN_CODE"
    ALREADY_ENROLLED = "ALREADY_ENROLLED"

    # Assignment
    ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND"

    # Journal
    JOURNAL_NOT_FOUND = "JOURNAL_NOT_FOUND"
    INVALID_WORKFLOW_STATE = "INVALID_WORKFLOW_STATE"
    REVISION_CONFLICT = "REVISION_CONFLICT"

    # Upload & Export
    UPLOAD_FAILED = "UPLOAD_FAILED"
    EXPORT_FAILED = "EXPORT_FAILED"

    # Infrastructure & Rate Limiting
    DATABASE_ERROR = "DATABASE_ERROR"
    REDIS_ERROR = "REDIS_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
